name: Dev Windows

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  dev-windows:
    runs-on: windows-latest
    timeout-minutes: 3600
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore Electron cache
        id: electron-cache
        uses: actions/cache@v4
        with:
          path: c:\electron
          key: electron-39.2.7-win32-x64

      - name: Download Electron if cache miss
        if: steps.electron-cache.outputs.cache-hit != 'true'
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri "https://github.com/electron/electron/releases/download/v39.2.7/electron-v39.2.7-win32-x64.zip" -OutFile "c:\electron.zip"
          Expand-Archive -Path  "c:\electron.zip" -DestinationPath c:\electron -Force
          ls c:\electron

      - name: Add Electron to PATH
        shell: pwsh
        run: |
          $electronPath = "c:\electron"
          "$electronPath" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Check Electron version
        run: electron.exe -v
        shell: pwsh

      - name: Boot
        shell: pwsh
        env:
          CF_TUNNEL: ${{ secrets.WIN_CF_TUNNEL }}
          JUPYTER_TOKEN: ${{ secrets.JUPYTER_TOKEN }}
        run: .github/workflows/scripts/windows.ps1

      - name: Maintain
        shell: pwsh
        run: .github/workflows/scripts/maintain.ps1


